-- MySQL Script generated by MySQL Workbench
-- Tue Nov  8 15:07:50 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema airbnb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `airbnb` ;

-- -----------------------------------------------------
-- Schema airbnb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airbnb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `airbnb` ;

-- -----------------------------------------------------
-- Table `airbnb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `airbnb`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `zipcode` VARCHAR(11) NOT NULL,
  `is_host` CHAR(1) NOT NULL DEFAULT 'F',
  `email_id` VARCHAR(256) NOT NULL,
  `password` VARCHAR(14) NOT NULL,
  `ssn` VARCHAR(45) NOT NULL,
  `phone_no` VARCHAR(15) NOT NULL,
  `birthdate` VARCHAR(10) NOT NULL COMMENT 'dd/mm/yyyy',
  `credit_card_no` VARCHAR(16) NULL,
  `exp_date` VARCHAR(5) NULL COMMENT 'mm/yy',
  `cvv` VARCHAR(4) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `airbnb`.`property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`property` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `airbnb`.`property` (
  `prop_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `host_id` INT UNSIGNED NOT NULL,
  `category` VARCHAR(45) NULL,
  `street` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `zipcode` VARCHAR(11) NOT NULL,
  `quantity` VARCHAR(45) NULL,
  `description` VARCHAR(500) NULL,
  `per_night_price` DOUBLE NOT NULL,
  `listed_time` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`prop_id`),
  CONSTRAINT `host_id_fk2`
    FOREIGN KEY (`host_id`)
    REFERENCES `airbnb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `host_id_fk2_idx` ON `airbnb`.`property` (`host_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `airbnb`.`billing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`billing` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `airbnb`.`billing` (
  `billing_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trip_id` INT UNSIGNED NULL,
  PRIMARY KEY (`billing_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `airbnb`.`trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`trip` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `airbnb`.`trip` (
  `trip_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `prop_id` INT UNSIGNED NOT NULL,
  `host_id` INT UNSIGNED NOT NULL,
  `billing_id` INT UNSIGNED NULL,
  `checkin_date` DATETIME NOT NULL,
  `checkout_date` DATETIME NOT NULL,
  `no_of_guests` INT NOT NULL,
  `trip_status` VARCHAR(45) NULL DEFAULT 'PENDING' COMMENT 'Values : ‘ACCEPTED’, ‘REJECTED’, ‘PENDING’',
  PRIMARY KEY (`trip_id`),
  CONSTRAINT `user_id_fk1`
    FOREIGN KEY (`user_id`)
    REFERENCES `airbnb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prop_id_fk1`
    FOREIGN KEY (`prop_id`)
    REFERENCES `airbnb`.`property` (`prop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `host_id_fk1`
    FOREIGN KEY (`host_id`)
    REFERENCES `airbnb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `billing_id_fk1`
    FOREIGN KEY (`billing_id`)
    REFERENCES `airbnb`.`billing` (`billing_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `user_id_fk1_idx` ON `airbnb`.`trip` (`user_id` ASC);

SHOW WARNINGS;
CREATE INDEX `prop_id_fk1_idx` ON `airbnb`.`trip` (`prop_id` ASC);

SHOW WARNINGS;
CREATE INDEX `host_id_fk1_idx` ON `airbnb`.`trip` (`host_id` ASC);

SHOW WARNINGS;
CREATE INDEX `billing_id_fk1_idx` ON `airbnb`.`trip` (`billing_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `airbnb`.`bidding`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`bidding` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `airbnb`.`bidding` (
  `bid_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME NULL DEFAULT now(),
  `max_bid_days` INT NULL DEFAULT 4,
  `expiry_date` DATETIME NULL,
  `host_min_amt` DOUBLE NULL,
  `max_bid_price` DOUBLE NULL,
  `max_bid_user_id` INT UNSIGNED NULL,
  PRIMARY KEY (`bid_id`),
  CONSTRAINT `max_bide_user_id_fk3`
    FOREIGN KEY (`max_bid_user_id`)
    REFERENCES `airbnb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `max_bide_user_id_fk3_idx` ON `airbnb`.`bidding` (`max_bid_user_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `airbnb`.`bidding_dtl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`bidding_dtl` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `airbnb`.`bidding_dtl` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid_id` INT UNSIGNED NULL,
  `bidder_id` INT UNSIGNED NULL,
  `bid_price` DOUBLE NULL,
  `bid_time` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  CONSTRAINT `bid_id`
    FOREIGN KEY (`bid_id`)
    REFERENCES `airbnb`.`bidding` (`bid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bidder_id`
    FOREIGN KEY (`bidder_id`)
    REFERENCES `airbnb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `bid_id_idx` ON `airbnb`.`bidding_dtl` (`bid_id` ASC);

SHOW WARNINGS;
CREATE INDEX `bidder_id_idx` ON `airbnb`.`bidding_dtl` (`bidder_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
